# Generated by Django 4.2.16 on 2024-11-19 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_transactions_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 13, 14, 53, 767600)),
        ),
    ]
