# Generated by Django 4.2.16 on 2024-12-27 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_transactions_datetime_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 27, 21, 18, 11, 470547)),
        ),
    ]
